CREATE TABLE PASSENGER_FLIGHT
(
    PASSENGER_ID NUMBER,
    FLIGHT_ID    NUMBER,
    CONSTRAINT PASSENGER_FLIGHT_PK PRIMARY KEY (PASSENGER_ID, FLIGHT_ID),
    CONSTRAINT PASSENGER_FK FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER (ID),
    CONSTRAINT FLIGHT_FK FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT (ID)
);