CREATE TABLE FLIGHT
(
    ID          NUMBER PRIMARY KEY,
    PLANE_ID    NUMBER        NOT NULL,
    DATE_FLIGHT DATE          NOT NULL,
    CITY_FROM   NVARCHAR2(20) NOT NULL,
    CITY_TO     NVARCHAR2(20) NOT NULL,
    CONSTRAINT PLANE_FK FOREIGN KEY (PLANE_ID) REFERENCES PLANE (ID)
);