CREATE TABLE PASSENGER
(
    ID            NUMBER PRIMARY KEY,
    LAST_NAME     NVARCHAR2(20)        NOT NULL,
    NATIONALITY   NVARCHAR2(20)        NOT NULL,
    DATE_OF_BIRTH DATE                 NOT NULL,
    PASSPORT_CODE NVARCHAR2(20) UNIQUE NOT NULL
);